name: "Release"

on:
  push:
    tags:
      - "*.*.*"

jobs:
  build:
    # Build the .NET standard 2.0 library
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.6
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4.0.0
        with:
          dotnet-version: 8.0.X
      - name: Install dependencies
        run: dotnet restore
      - name: Build with dotnet
        run: dotnet build --configuration Release
      - name: Test with dotnet
        run: dotnet test --configuration Release ./src/Costasdev.Uuidv7.Tests/Costasdev.Uuidv7.Tests.csproj
      - name: Preserve artifact for release
        uses: actions/upload-artifact@v4.3.3
        with:
          name: release
          path: src/Costasdev.Uuidv7/bin/Release/netstandard2.0/Costasdev.Uuidv7.dll

  publish:
    name: Package and publish
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.6
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4.0.0
        with:
          dotnet-version: 8.0.X
      - name: Download artifact
        uses: actions/download-artifact@v4.1.7
        with:
          name: release
          path: src/Costasdev.Uuidv7/bin/Release/netstandard2.0
      - name: Publish package to nuget.org
        run: dotnet nuget push src/Costasdev.Uuidv7/bin/Release/netstandard2.0/Costasdev.Uuidv7.dll --api-key ${{ secrets.NUGET_API_KEY }}
      - name: Authenticate to GitHub
        run: dotnet nuget add source --username arielcostas --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github https://nuget.pkg.github.com/arielcostas/index.json
      - name: Publish package to GitHub
        run: dotnet nuget push src/Costasdev.Uuidv7/bin/Release/netstandard2.0/Costasdev.Uuidv7.dll --api-key ${{ secrets.GITHUB_TOKEN }} --source github
      - name: Publish release
        uses: softprops/action-gh-release@v2.0.5

